import os
import sipconfig
from PyQt4 import pyqtconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "QWave4.sbf"

# Get the SIP configuration information.
config = pyqtconfig.Configuration()

# Run SIP to generate the code.
cmdline = " ".join([
    config.sip_bin,
    "-c", "../python",
    "-b", build_file,
    "-w",
    "-I", config.pyqt_sip_dir,
    "-I", ".",
    config.pyqt_sip_flags,
    "main.sip"
    ])

os.system(cmdline)
print(cmdline)

# Create the Makefile.
makefile = pyqtconfig.QtGuiModuleMakefile(config, build_file, makefile="../python/Makefile")

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_include_dirs = ["../src"]
makefile.extra_lib_dirs = ["../src/"]
makefile.extra_libs = ["qwave4"]

# Generate the Makefile itself.
makefile.generate()
